[tool.poetry]
name = "pipenv-poetry-migrate"
version = "0.1.1"
description = "simple migration script, migrate pipenv to poetry"
authors = ["Yoshiyuki HINO <yhinoz@gmail.com>"]
repository = 'https://github.com/yhino/pipenv-poetry-migrate'
homepage = 'https://github.com/yhino/pipenv-poetry-migrate'
readme = 'readme.md'

[tool.poetry.dependencies]
python = "^3.7"
tomlkit = "^0.5.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
black = "^19.10b0"
isort = {extras = ["pyproject"], version = "^4.3.21"}

[tool.poetry.scripts]
pipenv-poetry-migrate = "pipenv_poetry_migrate.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
exclude = """
(
    .venv
)
"""

[tool.isort]
include_trailing_comma = true
line_length = 88
multi_line_output = 3
